### ISSUE TITLE
Call to restaurants API fails with 500 response

### ISSUE THREAD

**Issue by adamreger** [jdbuysse/your-table-is-ready#1]
The call to the /restaurants API is failing with a 500 response, which is causing the application to not build the table

![Screen Shot 2020-09-15 at 8 54 04 PM](https://user-images.githubusercontent.com/7674182/93286955-9928d800-f795-11ea-9bfb-3bfb5fdb1093.png)

**Comment by jdbuysse** [comment]
Hi Adam, I took a quick look this morning, and this issue is the result of a null value in the authorization header where it expects an API key. I've hidden the key in an environment file and set that file to be untracked by version control. You can fix the issue by
creating an .env file in the root directory of the project and setting the API key as a global variable like so:
`REACT_APP_API_KEY=[your-api-key-here`] 

You can see where to use the global variable in the fetch request here:
```
`const fetchData = async function() {
    const { data } = await axios.get('https://code-challenge.spectrumtoolbox.com/api/restaurants', {
        headers: {
            Authorization: `Api-Key ${process.env.REACT_APP_API_KEY}`,
        }
    })
    return data;
}`
```

In the meantime I can send you a key via PM.

**Comment by jdbuysse** [comment]
Thank you for the issue, I am going to keep this open until I can implement some better and more descriptive error handling on the fetch request.

**Comment by adamreger** [comment]
Resolved by adding the .env with api key value to root directory
